# ===== BUILD STAGE =====
FROM eclipse-temurin:11-jdk AS build
WORKDIR /app

COPY pom.xml .
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
RUN mvn -B dependency:go-offline

COPY . .
RUN mvn clean package -DskipTests

# ===== RUNTIME STAGE =====
FROM tomcat:9-jdk11-temurin

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/target/vprofile-v2.war \
  /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
