# ===== BUILD STAGE =====
FROM eclipse-temurin:11-jdk AS build
WORKDIR /app

RUN apt-get update && \
    apt-get install -y maven git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/devopshydclub/vprofile-project.git
WORKDIR /app/vprofile-project
RUN git checkout docker && mvn clean package -DskipTests

# ===== RUNTIME STAGE =====
FROM tomcat:9.0.113-jdk11-temurin

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build \
  /app/vprofile-project/target/vprofile-v2.war \
  /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
